### ISSUE TITLE
wrong symmetrized Hamiltonian with vasp

### ISSUE THREAD

**Issue by apezol1** [ccao/WannSymm#2]
Dear WannSymm developers,

I'm currently facing a problem when running the code. I've used Vasp (5.4.1) with the wannier90 interface. I've used the seedame_hr.dat and POSCAR files in order to run wannsymm with the following input:
%%%%%%%%
DFTcode  = VASP

Spinors  = T

SeedName ='wannier90'

Use_POSCAR = 'POSCAR'
begin projections
Pt: s; px; py; pz; dz2; dx2-y2; dxy; dyz; dxz
end projections

nk_per_kpath = 101
begin kpath
X 0.500000  0.000000  0.500000  Y  0.500000  0.250000  0.750000
Y 0.500000  0.250000  0.750000  L  0.500000  0.500000  0.500000
L 0.500000  0.500000  0.500000  G  0.000000  0.000000  0.000000
end kpath
%%%%%%

In the above case I tested Pt with that given projection, however after the running the bands obtained for the symmetrized and original cases don't match. Is there any other flag I'm missing?.

Best regards,

**Comment by gxzhi** [comment]
> Dear WannSymm developers,
> 
> I'm currently facing a problem when running the code. I've used Vasp (5.4.1) with the wannier90 interface. I've used the seedame_hr.dat and POSCAR files in order to run wannsymm with the following input: %%%%%%%% DFTcode = VASP
> 
> Spinors = T
> 
> SeedName ='wannier90'
> 
> Use_POSCAR = 'POSCAR' begin projections Pt: s; px; py; pz; dz2; dx2-y2; dxy; dyz; dxz end projections
> 
> nk_per_kpath = 101 begin kpath X 0.500000 0.000000 0.500000 Y 0.500000 0.250000 0.750000 Y 0.500000 0.250000 0.750000 L 0.500000 0.500000 0.500000 L 0.500000 0.500000 0.500000 G 0.000000 0.000000 0.000000 end kpath %%%%%%
> 
> In the above case I tested Pt with that given projection, however after the running the bands obtained for the symmetrized and original cases don't match. Is there any other flag I'm missing?.
> 
> Best regards,

Change the order of orbitals in the _projections block_ to this one may fix this problem. If the problem is not fixed, please let me know.
```
begin projections
Pt: s; pz; px; py; dz2; dxz; dyz; dx2-y2; dxy
end projections
```

The explanation:
In Wannier90 code, cubic harmonics orbitals (such as pz, px, py) are always in pre-defined order which is independent of the orbital order in the _Projections block_ in the wannier90's input file.   
[ I have checked this feature in Wannier90 v2.1.0 and v3.1.0 ]

For example, the order of the three p (or five d) orbitals in Wannier90 code is
```
pz; px; py

dz2; dxz; dyz; dx2-y2; dxy
```

However, in our WannSymm code, the order of orbitals is exactly that order of orbitals written in the input file. 
Therefore, if WannSymm is used as post-processing code of Wannier90 code, the order of orbitals should follows Wannier90's definition.

**Comment by apezol1** [comment]
Thank you very much for the reply. I think the problem was VASP(whether this version or the actual compilation in the cluster) because everything worked perfect with QE.

Best regards,
